namespace: lucheon
name: k8s_applications_utils
version: 1.0.0
readme: README.md
authors:
- Etienne Barbier <etienne.barbier1@grenoble-inp.org>
description: Collection of utils usefull to deploy application on a kubernetes cluster
license:
- GPL-2.0-or-later
tags: []
dependencies: {}
repository: https://github.com/Lucheon/ansible-k8s-applications-utils
